document.addEventListener('DOMContentLoaded', () => {
    const appForm = document.getElementById('appForm');
    const assetGrid = document.getElementById('assetGrid');
    const previewFrame = document.getElementById('previewFrame');
    const downloadBtn = document.getElementById('downloadBtn');
    const downloadStatus = document.getElementById('downloadStatus');
    const generateBtn = document.getElementById('generateBtn');

    // Load assets preview
    const assets = [
        'assets/logo-lld-neon.png',
        'assets/logo-ll-metal.png',
        'assets/logo-ln-circle.png',
        'assets/character-rb.png',
        'assets/texture-carbon.png',
        'assets/video-promo.mp4'
    ];
    assetGrid.innerHTML = assets.map(src => `
        <div class="asset-item">
            ${src.endsWith('.mp4') ? `<video src="${src}" muted loop playsinline></video>` : `<img src="${src}" alt="Asset">`}
        </div>
    `).join('');

    let generatedAppHTML = '';
    let generatedAppFilename = 'app.html';

    generateBtn.addEventListener('click', () => {
        if (!appForm.checkValidity()) {
            appForm.reportValidity();
            return;
        }
        const appName = document.getElementById('appName').value.trim();
        const appType = document.getElementById('appType').value;
        const features = document.getElementById('features').value.trim();
        const theme = document.getElementById('theme').value;

        const themeStyles = {
            'neon-cyber':    'background:linear-gradient(135deg,#0a0a0a,#1a0a2e);color:#00ffff;',
            'carbon-metal':  'background:linear-gradient(135deg,#1c1c1c,#2e2e2e);color:#c0c0c0;',
            'dark-gradient': 'background:linear-gradient(135deg,#0d0d0d,#16213e,#0f3460);color:#ffffff;'
        };
        const bodyStyle = themeStyles[theme] || themeStyles['neon-cyber'];

        const featureList = features
            ? features.split(',').map(f => `<li>${f.trim()}</li>`).join('')
            : '<li>Responsive layout</li>';

        const generatedHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${appName}</title>
  <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&display=swap" rel="stylesheet">
  <style>
    *{margin:0;padding:0;box-sizing:border-box}
    body{font-family:'Orbitron',monospace;${bodyStyle}min-height:100vh;padding:3rem 2rem;}
    h1{font-size:clamp(2rem,6vw,4rem);margin-bottom:1rem;text-shadow:0 0 20px currentColor;}
    p{margin-bottom:0.75rem;opacity:0.85;}
    ul{list-style:none;padding:0;display:flex;flex-wrap:wrap;gap:0.75rem;margin-top:1rem;}
    li{padding:0.5rem 1.25rem;border:1px solid currentColor;border-radius:50px;font-size:0.85rem;}
    img{width:160px;margin-top:2rem;filter:drop-shadow(0 0 10px currentColor);}
  </style>
</head>
<body>
  <h1>${appName}</h1>
  <p>Type: <strong>${appType}</strong></p>
  <p>Theme: <strong>${theme}</strong></p>
  <p>Features:</p>
  <ul>${featureList}</ul>
  <img src="assets/logo-ln-circle.png" alt="Logo">
  <p style="margin-top:2rem;font-size:0.75rem;opacity:0.5;">Generated by Lavaz Studio &mdash; Lavaz Life Designs</p>
</body>
</html>`;

        previewFrame.srcdoc = generatedHTML;
        downloadBtn.disabled = false;
        downloadStatus.textContent = `Generated: ${appName} (${appType})`;
        generatedAppHTML = generatedHTML;
        generatedAppFilename = appName.replace(/\s+/g, '-').toLowerCase() + '.html';
    });

    downloadBtn.addEventListener('click', () => {
        if (!generatedAppHTML) return;
        const link = document.createElement('a');
        link.href = 'data:text/html;charset=utf-8,' + encodeURIComponent(generatedAppHTML);
        link.download = generatedAppFilename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        downloadStatus.textContent = `Downloaded: ${generatedAppFilename}`;
    });

    // Smooth scroll for nav
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', (e) => {
            e.preventDefault();
            const target = document.querySelector(anchor.getAttribute('href'));
            if (target) target.scrollIntoView({ behavior: 'smooth' });
        });
    });
});